### ISSUE TITLE
GNU Make errors

### ISSUE THREAD

**Issue by nrydevops** [keybase/triplesec#64] opened 2018-10-03 19:46 UTC
I am getting the following errors when trying to run "make test"
  ☑ checked spec version 3
✔ triplesec.iced: check_spec
In twofish.iced/ecb_tbl: TypeError: Cannot read property 'length' of undefined
✔ wordarray.iced: compare_utf8
✔ wordarray.iced: test_cmp_ule_1
✖ Failure due to test configuration issues
Tests: 35/36 passed
Makefile:56: recipe for target 'test-server' failed
make: *** [test-server] Error 255
![triplesec_make_error](https://user-images.githubusercontent.com/39569902/46435079-7a091b00-c723-11e8-9e2f-f49578efb509.PNG)

How can I fix this?

**Comment by maxtaco** [comment] 2018-10-03 19:59
which version of node are you running?

**Comment by heronhaye** [comment] 2018-12-04 15:36
Hi @nrydevops, I couldn't repro on 11 or 8.12.0. Could you try again?

**Comment by heronhaye** [comment] 2018-12-18 22:47
Closed as could not reproduce; please make a new issue if you run into this again.

**Closed by heronhaye** 2018-12-18 22:47 UTC
